### ISSUE TITLE
Item Owner can Buy his own Items

### ISSUE THREAD

**Issue by PocketMiner92** [GommeAWM/Auction#1]
Try to sell a Item
Try to buy youre Item.

**Comment by GommeAWM** [comment]
i tried, works fine

**Comment by PocketMiner92** [comment]
But why should the Owner of the sell Item can Buy his own Item?

**Comment by GommeAWM** [comment]
why not maybe no one buys his item and he wants to put a new item up for auction but he has reached the max slots in the auction and can't put up new items and has to wait for the timer to go to zero but that's long , now he can buy his item and get a free spot in the auction and doesn't have to wait for the timer.
