### ISSUE TITLE
infinite money

### ISSUE THREAD

**Issue by luannnhock1310** [GommeAWM/Auction#3]
There is a bug, they can make infinite money from their own items!
Video:
https://www.youtube.com/watch?v=Fq-YnFJ_c0Y

**Comment by PocketMiner92** [comment]
@GommeAWM

**Comment by PocketMiner92** [comment]
Report this Plugin at Cloudburst
It must be deleted

**Comment by PocketMiner92** [comment]
@luannnhock1310

**Comment by luannnhock1310** [comment]
he deleted all posts related to him in cloudburstmc

**Comment by luannnhock1310** [comment]
@PocketMiner92

**Comment by PocketMiner92** [comment]
Contact a Cloudburst Owner
He can delete this Plugin.

**Comment by GommeAWM** [comment]
Fixed the Bug with dupe Money!!
